import "./design-system.css";
import "./global.css";
import { AuthProvider } from "@/src/contexts/AuthContext";

export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}